### ISSUE TITLE
Spacebar Not making Loh Go

### ISSUE THREAD

**Issue by rexxcastle** [p3lim-wow/BetterWorldQuests#1]
Spacebar Not making Loh Go.  it does nothing when i spam it.

**Comment by p3lim** [comment]
Do you get a message on the screen when you start the worldquest after talking to the NPC?
What faction is your character and which zone were you in?

**Comment by rexxcastle** [comment]
It says "Spam spacebar to complete" or something like that.  When I press spacebar i get the error "cant do that right now" and nothing happens.   I am Horde,   I was in Zulzadar Last night and currently in Vol'Dun this morning,

This has never worked for me since getting it no matter the zone.

**Comment by p3lim** [comment]
Thank you for the information. I use the same bindings.

Could I have a list of all your addons? I'm suspecting another addon is interfering with the rebinding process.

**Comment by rexxcastle** [comment]
Zero addons other than yours.  That was the first thing I tested on my other PC

**Comment by rexxcastle** [comment]
Any idea if there is a way to make it work with ElvUI as that is a pretty popular UI?

**Comment by p3lim** [comment]
I'll take a look, thanks for the information.

**Comment by p3lim** [comment]
If you would like to test that possible fix, please do so by downloading from GitHub and replacing the addon files.
