### ISSUE TITLE
Spacebar not working with "We'll Make an Aspirant Out of You"

### ISSUE THREAD

**Issue by bababbel** [p3lim-wow/BetterWorldQuests#11]
When I use Spacebar during the world quest "We'll Make an Aspirant Out of You", I get the error message "I can't do that right now".
I have ElvUI installed and can confirm that it does work with ElvUI disabled. Can this be fixed? I really don't want to disable ElvUI everytime I do the quest.

**Comment by LiangYuxuan** [comment]
This is like #1. I did a test and find out it should be `ElvUI_Bar1Button%d` instead of `OverrideActionBarButton%d`, and it works well.

**Comment by p3lim** [comment]
I have a possible fix that generalizes it, but the world quest hasn't shown up in 5 days for me.

**Comment by p3lim** [comment]
Give this a try:
https://github.com/p3lim-wow/BetterWorldQuests/suites/1921475249/artifacts/37825493

**Comment by bababbel** [comment]
Thank you! I will as soon as I see the quest.
