### ISSUE TITLE
Latest version has broken some WQ shortcuts.

### ISSUE THREAD

**Issue by Cluuey** [p3lim-wow/BetterWorldQuests#14]
Since updating to 13 I noticed some of the things which used to happen don't.
I just rolled back to the previous version, still in my downloads folder (11), to test and previous functionality has been restored.

Quests I know broke:
Tough Crowd: It's no longer adding the skull to the abberations.
Into the Unknown: it is no longer choosing the dialogue options.

I don't think it's working with the quests where you can spam the space bar to finish them, also the rare in Korthia, not that it's important there as there's only one button anyway. ;-)

**Comment by p3lim** [comment]
Please see https://www.curseforge.com/wow/addons/quest-automation / https://github.com/p3lim-wow/QuestAutomation

**Comment by Cluuey** [comment]
Oh, thanks.
Sorry for the ticket then, I hadn't seen the in game message but I did check the change log on Wowinterface.

Thanks for your time, it is greatly appreciated.

**Comment by p3lim** [comment]
See [changes in 90100.12](https://github.com/p3lim-wow/BetterWorldQuests/blob/master/CHANGELOG.md#changes-in-9010012-release) :)
