### ISSUE TITLE
Unhandled currency

### ISSUE THREAD

**Issue by fraerie** [p3lim-wow/BetterWorldQuests#32]
**Describe the bug**
BWQ is spamming my chat channel "Unhandled currency: ID 2245" while in Zarralek Caverns

**How to reproduce**
Load BetterWorldQuests-100100.23-Release and enter Zarralek Caverns

**What did you expect?**
It to not spam an error

**Screenshots**

**Comment by p3lim** [comment]
You're looking for this addon: https://www.curseforge.com/wow/addons/broker_worldquests

**Comment by fraerie** [comment]
Indeed I am - I worked it out after logging this bug
