### ISSUE TITLE
133x ...rd_SharedMapDataProviders/WorldQuestDataProvider.lua:330: attempt to index local 'tagInfo' (a nil value) 

### ISSUE THREAD

**Issue by kittykatmax** [p3lim-wow/BetterWorldQuests#36]
**Describe the bug**
I think I figured it out...I am now guessing it doesn't play well with Angrier World Quests.  My other PC, with JUST Angrier World Quests was fine.  I had both running on the PC I reported this from, and I had just installed Better World Quests (thought it was on both PCs, it wasn't).  Disabling Angrier World Quests, and now I'm not getting the error.

**How to reproduce**
Hit "M" to launch Map/Also run Angrier World Quests (each is fine on its own)

**What did you expect?**
Opening map not to throw an error once per second.

**Bugsack**

`188x ...rd_SharedMapDataProviders/WorldQuestDataProvider.lua:330: attempt to index local 'tagInfo' (a nil value)
[string "@Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua"]:330: in function `AddWorldQuest'
[string "@BetterWorldQuests/PinProvider.lua"]:161: in function `RefreshAllData'
[string "@Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua"]:134: in function `ClearFocusedQuestID'
[string "@Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua"]:80: in function <...rd_SharedMapDataProviders/WorldQuestDataProvider.lua:79>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:178: in function <SharedXML/CallbackRegistry.lua:177>
[string "=[C]"]: ?
[string "@SharedXML/CallbackRegistry.lua"]:181: in function `TriggerEvent'
[string "@Blizzard_WorldMap/Blizzard_WorldMap.lua"]:427: in function <...rfaceBlizzard_WorldMap/Blizzard_WorldMap.lua:426>
[string "=[C]"]: in function `ClearFocusedQuestID'
[string "@FrameXML/QuestMapFrame.lua"]:695: in function <FrameXML/QuestMapFrame.lua:691>
[string "=[C]"]: ?
[string "=[C]"]: in function `QuestMapFrame_CloseQuestDetails'
[string "@FrameXML/QuestMapFrame.lua"]:712: in function `QuestMapFrame_UpdateSuperTrackedQuest'
[string "@FrameXML/QuestMapFrame.lua"]:238: in function <FrameXML/QuestMapFrame.lua:212>

Locals:
self = <table> {
 GetBountyInfo = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:156
 OnClearFocusedQuestID = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:79
 EvaluateCheckBounties = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:63
 OnMapInsetMouseLeave = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:46
 AddWorldQuest = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:319
 OnSuperTrackingChanged = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:266
 SetMatchWorldMapFilters = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:3
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:50
 registeredEvents = <table> {
 }
 PingQuestID = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:160
 owningMap = WorldMapFrame {
 }
 ShouldSupertrackHighlightInfo = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:285
 activePins = <table> {
 }
 ShouldOverrideShowQuest = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:207
 ShouldShowQuest = <function> defined @AngrierWorldQuests/QuestFrame.lua:1095
 IsUsingSpellEffect = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:23
 OnCanvasSizeChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:58
 GetMapQuests = <function> defined @BetterWorldQuests/PinProvider.lua:78
 markActiveQuests = true
 checkBounties = true
 usesSpellEffect = true
 IsMarkingActiveQuests = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:94
 OnRemoved = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:117
 OnAdded = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:98
 OnMapChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:74
 matchWorldMapFilters = true
 GetMap = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:70
 ClearFocusedQuestID = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:132
 SignalEvent = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:97
 GetPinTemplate = <function> defined @BetterWorldQuests/PinProvider.lua:59
 OnShow = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:188
 OnSetFocusedQuestID = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:75
 HandleMouseAction = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:103
 spellEffectPin = CinematicModel {
 }
 suppressedQuests = <table> {
 }
 OnMapInsetSizeChanged = <function> defined @Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua:38
 IsCheckingBounties = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:59
 HandleClick = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:46
 SetCheckBounties = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:50
 SetUsesSpellEffect = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:15
 DoesWorldQuestInfoPassFilters = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:202
 OnPingQuestID = <function> defined @Blizzard_SharedMapDataProviders/WorldQuestDataProvider.lua:83
 OnE`

**Comment by p3lim** [comment]
Which map/zone?

**Comment by p3lim** [comment]
Added a clause but never got a response.
