### ISSUE TITLE
An option to make icons smaller - Fullscreen map

### ISSUE THREAD

**Issue by Nillx** [p3lim-wow/BetterWorldQuests#38]
Hello, im using Leatrix Map addon that makes the fullscreen map smaller and resizable. Last update made WQ icons a bit bigger and they look looks quite weird, would be nice if there was a way to make them smaller.

**Comment by p3lim** [comment]
This is something that has been requested frequently, and is something I've been slowly working on adding support for, although I wanted to it properly and make a small config framework for myself that is easier to maintain than my previous attempts at this.

Progress is looking good, just need to give it a bit more time for testing to ensure I've squashed all the bugs.

**Comment by Nillx** [comment]
No problem and thanks! I love the addon.

**Comment by p3lim** [comment]
Please try this alpha version:
https://github.com/p3lim-wow/BetterWorldQuests/suites/18292572852/artifacts/1057874389

**Comment by Nillx** [comment]
Sorry for the late answer. Tried that version and it works great!

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/BetterWorldQuests/commit/2b11185b075f012d767bc712fa03b58c8f81d61f
