### ISSUE TITLE
Translation: 

### ISSUE THREAD

**Issue by BlueNightSky** [p3lim-wow/BetterWorldQuests#39]
### Which locale are these translations for?

zhTW (Chinese, Traditional, Taiwan)

### "Map pin scale"

地圖標記點大小

### "The scale of world quest pins on the current map"

在當前地圖的世界任務標記點大小

### "Overview pin scale"

總覽標記點大小

### "The scale of world quest pins on a parent/continent map"

在大陸地圖的世界任務標記點大小

### "Pin size zoom factor"

標記點大小縮放係數

### "How much extra scale to apply when map is zoomed"

縮放地圖時要應用多少額外的縮放

**Comment by p3lim** [comment]
Thanks :)

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/BetterWorldQuests/commit/b3d79e052a0da6555b2e0840fc2eb1d9771240e0
