### ISSUE TITLE
An error when using quest item

### ISSUE THREAD

**Issue by Nethermoure** [p3lim-wow/BetterWorldQuests#55]
Got errors when tried to use quest items from quests list -

1x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterWorldQuests' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by p3lim** [comment]
Same cause as #53, if you want to monitor the eventual progress you can hit the subscribe button on that issue.
