### ISSUE TITLE
Icons obscure entire map when viewing "World -> Azeroth"

### ISSUE THREAD

**Issue by justinkb** [p3lim-wow/BetterWorldQuests#56]
You can't even see the landmasses of the Dragon Isles, Kul Tiras, Zandalar and Broken Isles due to all the big icons.

We probably need another scaling option and apply it specifically to this view

**Comment by p3lim** [comment]
That last commit adds an option to hide the pins on the azeroth map entirely, as even with the pins being tiny they still make it difficult to navigate.
