### ISSUE TITLE
 translations for zhCN

### ISSUE THREAD

**Issue by byezero** [p3lim-wow/BetterWorldQuests#60]
### Which locale are these translations for?

zhCN (Chinese, Simplified, PRC)

### "Map pin scale"

地图标记缩放

### "The scale of world quest pins on the current map"

当前地图上世界任务标记的缩放比例。

### "Overview pin scale"

 概览地图标记缩放。

### "The scale of world quest pins on a parent/continent map"

在父地图/大陆地图上的世界任务标记的缩放比例。

### "Pin size zoom factor"

标记大小缩放因子。

### "How much extra scale to apply when map is zoomed"

当地图放大时应用的额外缩放比例。

### "Show events on continent"

在大陆地图上显示事件。

### "Show on Azeroth"

在艾泽拉斯上显示。

### "Hold key to hide"

按住键以隐藏。

### "Hold this key to temporarily hide all world quests"

按住此键临时隐藏所有世界任务。

**Comment by p3lim** [comment]
Thanks!
