### ISSUE TITLE
Error with new patch

### ISSUE THREAD

**Issue by tommy610** [p3lim-wow/BetterWorldQuests#75]
**Describe the bug**

4x ...zard_SharedMapDataProviders/VignetteDataProvider.lua:14: attempt to index local 'vignetteInfo' (a nil value)
[string "@Blizzard_SharedMapDataProviders/VignetteDataProvider.lua"]:14: in function `GetPinTemplate'
[string "@BetterWorldQuests/provider.lua"]:66: in main chunk

Locals:
self = nil
vignetteInfo = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'vignetteInfo' (a nil value)"

**How to reproduce**

**What did you expect?**

**Screenshots**

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/BetterWorldQuests/commit/f2646283c27fd6f9cd3e7e1d532578b5979d9f82
