### ISSUE TITLE
Error message since last update in Loh.lua

### ISSUE THREAD

**Issue by stamicvs** [p3lim-wow/BetterWorldQuests#8]
Hi p3lim,

since the last update of BetterWorldQuest i get the following error-messages:
2x [ADDON_ACTION_BLOCKED] AddOn 'BetterWorldQuests' tried to call the protected function 'ClearOverrideBindings()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `ClearOverrideBindings'
BetterWorldQuests\Helpers/Loh.lua:130: in function `Uncontrol'
BetterWorldQuests\Helpers/Loh.lua:84: in function <BetterWorldQuests\Helpers/Loh.lua:57>

Locals:
InCombatSkipped

**Comment by stamicvs** [comment]
Hi p3lim,

thank you very much for the immediate fix and respose.
Unfortunately there are still some error messages showing up.
I don't know why those errors are occurring, I am in Shadowlands and not even doing a Loh quest:

`8x [ADDON_ACTION_BLOCKED] AddOn 'BetterWorldQuests' tried to call the protected function 'ClearOverrideBindings()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `ClearOverrideBindings'
BetterWorldQuests\Helpers/Loh.lua:130: in function `Uncontrol'
BetterWorldQuests\Helpers/Loh.lua:84: in function <BetterWorldQuests\Helpers/Loh.lua:57>

Locals:
InCombatSkipped`

**Comment by p3lim** [comment]
You sure you've updated the addon? Those line numbers don't match up at all.

**Comment by stamicvs** [comment]
Yes, I am sure, it shows 90000.7-Release in the toc-file.
I am still getting these errors after questing a little while. I will test again with other addons unloaded.

**Comment by p3lim** [comment]
Please uninstall the addon completely and install it again, the error you're getting corresponds to the 90000.6-Release files, not the newest one, so something must have gotten mixed up.
